-- =========================================================================
/*
	Plik do zadania 3: 01_ddl.sql
	Tytuł: Tworzy strukturę tabel dla: udanych rezerwacji, licznika rezerwacji i logów.
	Data: 2025-08-31
	Uwagi:  
  1. reservation_tickets
     - idr RAW(16) PRIMARY KEY: unkalny identyfikator rezerwacji (UUID z sys_guid())
     - pesel VARCHAR2(11) NOT NULL: PESEL osoby rezerwującej
     - date_reseration DATE DEFAULT SYSDATE: data dokonania rezerwacji
     - opcjonalnie: ograniczenie 1 rezewacja na PESEL (UNIQUE INDEX)

  2. reservation_counter
     - counter_id NUMBER PRIMARY KEY: zawsze jeden wiersz
     - reserved NUMBER DEFAULT 0: licznik już zarezerwowanych biletów
     - używany UPDATE do zwiększania licznika zamiast COUNT całej tabeli (wydajność)

  3. log_reservation
     - date_register DATE DEFAULT SYSDATE: data próby rejestracji
     - status NUMBER: status próby rezerwacji
     - idr RAW(16): UUID przydzielony jeśli rezerwacja się powiodła, NULL w przeciwnym wypadku
*/
-- =========================================================================

CREATE TABLE reservation_tickets (
    idr 			  RAW(16) PRIMARY KEY,        
    pesel 			  VARCHAR2(11) NOT NULL,   
    date_reservation  DATE DEFAULT SYSDATE 
);
CREATE UNIQUE INDEX uq_reservation_pesel ON reservation_tickets(pesel);


CREATE TABLE reservation_counter (
    counter_id        NUMBER PRIMARY KEY, 
    reserved          NUMBER DEFAULT 0   
);

INSERT INTO reservation_counter (counter_id, reserved) VALUES (1, 0);



CREATE TABLE log_reservation (
    log_id 			  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pesel 			  VARCHAR2(11) NOT NULL,
    date_register	  DATE DEFAULT SYSDATE, 
    status    		  NUMBER, 
    idr 		      RAW(16)
);





